### ISSUE TITLE
请教cordova

### ISSUE THREAD

**Issue by E1evenCc** [huangliop/BaiduLocation4Cordova#2]
哥子，我看了你写的几个cordova插件感觉你对这方面技术有研究，黑在行，想请教一下具体的问题。你方便的话看到回个信嘛 VX：wxid_4p1x40tp4a2m22

**Comment by Emiem2017** [comment]
哥子，老师喊我们搞一个webApp，用了下你的定位插件，鬼晓得现在遇到了瓶颈，就是有点问题想问一下，你方便的话能不能加下楼上那个兄弟的微信，么么哒。。。

**Comment by huangliop** [comment]
> 哥子，我看了你写的几个cordova插件感觉你对这方面技术有研究，黑在行，想请教一下具体的问题。你方便的话看到回个信嘛 VX：wxid_4p1x40tp4a2m22

不好意思，现在才看到你的提问。我想可能你现在已经解决问题了。如果还需要我帮助，就在这里留言吧
